openapi: 3.1.0
x-stoplight:
  id: gr7tm5a03g740
info:
  title: OpenAPI
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  '/players/id/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      summary: Get Player by Username
      tags: []
      responses:
        '200':
          description: Player Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Player'
              examples:
                Get User Alice Smith:
                  value:
                    id: 142
                    firstName: Alice
                    lastName: Smith
                    email: alice.smith@gmail.com
                    dateOfBirth: '1997-10-31'
                    emailVerified: true
                    signUpDate: '2019-08-24'
        '404':
          description: User Not Found
      operationId: get-player-by-id
      description: Retrieve the information of the player with the matching id
  '/players/name/{name}':
    parameters:
      - schema:
          type: string
        name: name
        in: path
        required: true
    get:
      summary: Get Player by ID
      tags: []
      responses:
        '200':
          description: Player Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Player'
        '404':
          description: Player Not Found
      operationId: get-player-by-name
      description: ''
  /servers/:
    get:
      summary: Get Server list
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Server'
      operationId: get-servers
components:
  schemas:
    Player:
      title: Player
      x-stoplight:
        id: be41fcacb2693
      type: object
      examples: []
      properties:
        id:
          $ref: '#/components/schemas/PlayerID'
          description: Unique identifier for the given user.
        name:
          type: string
      required:
        - id
    Weapon:
      title: Weapon
      x-stoplight:
        id: 7zc6t20eh3pcc
      type: object
      properties:
        id:
          $ref: '#/components/schemas/WeaponID'
        internal:
          type: string
          example: mp_weapon_sniper
        name:
          type: string
          example: Kraber
        description:
          type: string
        image:
          type: string
          format: uri
          example: 'https://static.wikia.nocookie.net/titanfall_gamepedia/images/8/8b/Icon_kraber.png'
      required:
        - id
        - internal
    Map:
      title: Map
      x-stoplight:
        id: hoh2m6pr6gli7
      type: object
      properties:
        id:
          $ref: '#/components/schemas/MapID'
        internal:
          type: string
          example: mp_angel_city
        name:
          type: string
        description:
          type: string
        image:
          type: string
          format: uri
      required:
        - id
        - internal
    Server:
      title: Server
      x-stoplight:
        id: hjfwmi2ae419o
      type: object
      properties:
        id:
          type: string
        token:
          type: string
        name:
          type: string
    Kill:
      title: Kill
      x-stoplight:
        id: a9q2tvsts3z32
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        server:
          type: string
          example: fvnkhead's 7v7
        attacker:
          $ref: '#/components/schemas/PlayerID'
        attacker_type:
          type: string
        attacker_weapon:
          $ref: '#/components/schemas/WeaponID'
        victim:
          $ref: '#/components/schemas/PlayerID'
        victim_weapon:
          $ref: '#/components/schemas/WeaponID'
        map:
          $ref: '#/components/schemas/MapID'
        distance:
          type: number
          example: 35.45
        date:
          type: string
          format: date-time
          readOnly: true
      required:
        - server
        - attacker_type
        - victim
    PlayerID:
      title: EntityID
      x-stoplight:
        id: 9icavmq5bgsqp
      type: integer
    WeaponID:
      title: WeaponID
      x-stoplight:
        id: p92aomkxku2po
      type: integer
    MapID:
      title: MapID
      x-stoplight:
        id: zoazw8eoi7qwr
      type: integer
